In [ ]:
import torch

In [2]:
x = torch.randn(10**6).cuda()

In [ ]:
x - 2

tensor([ 0.1832,  1.0823, -1.1020, -2.2206, -0.6066, -0.6003, -1.8771, -1.5581,
        -0.5125,  0.0037], device='cuda:0')

In [4]:
x - 3

tensor([-1.8168, -0.9177, -3.1020, -4.2206, -2.6066, -2.6003, -3.8771, -3.5581,
        -2.5125, -1.9963], device='cuda:0')

In [5]:
x - 4

tensor([-2.8168, -1.9177, -4.1020, -5.2206, -3.6066, -3.6003, -4.8771, -4.5581,
        -3.5125, -2.9963], device='cuda:0')